-- ============================================
-- AI 每日新闻表 + RLS 公开读
-- 在 Supabase Dashboard → SQL Editor 中执行
-- ============================================

-- 1. 建表
create table if not exists news_items (
  id            bigint generated by default as identity primary key,
  published_date date not null default current_date,
  title         text not null,
  title_en      text,
  url           text not null unique,
  summary_zh    text not null,
  score         int  not null check (score between 1 and 10),
  source        text,
  lang          text check (lang in ('zh','en')),
  created_at    timestamptz not null default now()
);

-- 按日期+分数查询的索引
create index if not exists idx_news_date_score
  on news_items (published_date desc, score desc);

-- 2. 开启 RLS
alter table news_items enable row level security;

-- 3. 公开读策略（任何人可 SELECT）
drop policy if exists "public read news" on news_items;
create policy "public read news"
  on news_items for select
  using (true);

-- 注意：没有 INSERT/UPDATE/DELETE 策略 → 匿名用户无法写。
-- 流水线使用 service_role key 写入（service_role 绕过 RLS）。
