create table if not exists news_items (
  id            bigint generated by default as identity primary key,
  published_date date not null default current_date,
  title         text not null,
  title_en      text,
  url           text not null unique,
  summary_zh    text not null,
  score         int  not null check (score between 1 and 10),
  source        text,
  lang          text check (lang in ('zh','en')),
  created_at    timestamptz not null default now()
);
create index if not exists idx_news_date_score on news_items (published_date desc, score desc);
alter table news_items enable row level security;
drop policy if exists "public read news" on news_items;
create policy "public read news" on news_items for select using (true);
